#ifndef ITEAFUNCTORCLASS_STRINGPAL_GLOBAL_H
#define ITEAFUNCTORCLASS_STRINGPAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ITEAFUNCTORCLASS_STRINGPAL_LIBRARY)
#  define ITEAFUNCTORCLASS_STRINGPALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ITEAFUNCTORCLASS_STRINGPALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ITEAFUNCTORCLASS_STRINGPAL_GLOBAL_H
